### ISSUE TITLE
请问这个数据集您还有存档嘛

### ISSUE THREAD

**Issue by wy-st** [FighterLYL/GraphNeuralNetwork#36]
我登录https://raw.githubusercontent.com/kimiyoung/planetoid/master/data这个网站不能直接下载数据。代码按您的粘过来报错如下：

Traceback (most recent call last):

  File "D:\练习\learning\GCN_KEY.py", line 257, in <module>
    dataset = CoraData().data

  File "D:\练习\learning\GCN_KEY.py", line 70, in __init__
    self.maybe_download()

  File "D:\练习\learning\GCN_KEY.py", line 122, in maybe_download
    "{}/{}".format(self.download_url, name), save_path)

  File "D:\练习\learning\GCN_KEY.py", line 157, in download_data
    data = urllib.request.urlopen(url)

  File "D:\anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "D:\anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)

  File "D:\anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)

  File "D:\anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)

  File "D:\anaconda3\lib\urllib\request.py", line 1362, in https_open
    context=self._context, check_hostname=self._check_hostname)

  File "D:\anaconda3\lib\urllib\request.py", line 1321, in do_open
    raise URLError(err)

URLError: <urlopen error [Errno 11004] getaddrinfo failed>

**Comment by FighterLYL** [comment]
请参考这个问题 #17

**Comment by wy-st** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"FighterLYL"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 晚上10:15
收件人:&nbsp;"FighterLYL/GraphNeuralNetwork"<GraphNeuralNetwork@noreply.github.com&gt;;
抄送:&nbsp;"Mr.Pro"<1207918198@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FighterLYL/GraphNeuralNetwork] 请问这个数据集您还有存档嘛 (#36)





 
请参考这个问题 #17
